### ISSUE TITLE
คิดหัวข้อโปรเจค

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#1]
คิดหัวข้อโปรเจคประเภท เกม ระบบ ฯลฯ

**Comment by ApichayaUWU** [comment]
not game but
แนวคิด : เป็นโปรแกรมง่ายๆเกี่ยวกับวิชาฟิสิกส์เรื่องเลนส์กับกระจกที่เรากำลังเรียนอยู่ 

แบบที่1 อาจจะทำเป็นcalculator ที่รับค่าตัวแปรพวก u v f m c ประเภทเลนส์หรือกระจก แล้วก็outputออกมาเป็นรายละเอียดลักษณะภาพที่เกิด กับเลนส์กระจกที่ใช้ ประมาณนี้
Or
แบบที่2 เป็นควิซที่สุ่มโจทย์มาให้คนใช้ลองตอบคำถามให้ถูก โปรแกรมจะสุ่มตัวแปรพวก u v f m c ไปเรื่อยๆ ฉะนั้นทุกข้อจะไม่มีการซ้ำกัน แล้วก็ให้ผู้เล่นตอบข้อมูลที่หายไป ตอบถูกก็ได้คะแนน

ทั้งสองแบบน่าจะต้องทำให้โปรแกรมมีการเจนภาพdiagramจากโจทย์ด้วยตัวเองได้ด้วย

**Comment by penpizza** [comment]
[หัวข้อโปรเจค.pdf](https://github.com/MindIssawara/C-Project/files/10703728/default.pdf)

**Comment by l3eluGA** [comment]
เสนอ เกม Minesweeper(เกมกู้ระเบิด) :คิดว่าใช้เรื่องarray2มิติทำได้นะ
![IMG_0901](https://user-images.githubusercontent.com/110966223/218003019-96d79379-87ee-4ca4-8a0f-fbe60610b484.jpeg)

**Comment by PAWEENNUTpuyfai** [comment]
ลองเป็นเกมไพ่แบบslaveไหมโดยเราเป็นคนเล่นคนเดียวแล้วที่เหลือก็สร้างเป็นบอท3ตัวแล้วเล่นกับผู้เล่นไหม

**Comment by MindIssawara** [comment]
> not game but แนวคิด : เป็นโปรแกรมง่ายๆเกี่ยวกับวิชาฟิสิกส์เรื่องเลนส์กับกระจกที่เรากำลังเรียนอยู่
> 
> แบบที่1 อาจจะทำเป็นcalculator ที่รับค่าตัวแปรพวก u v f m c ประเภทเลนส์หรือกระจก แล้วก็outputออกมาเป็นรายละเอียดลักษณะภาพที่เกิด กับเลนส์กระจกที่ใช้ ประมาณนี้ Or แบบที่2 เป็นควิซที่สุ่มโจทย์มาให้คนใช้ลองตอบคำถามให้ถูก โปรแกรมจะสุ่มตัวแปรพวก u v f m c ไปเรื่อยๆ ฉะนั้นทุกข้อจะไม่มีการซ้ำกัน แล้วก็ให้ผู้เล่นตอบข้อมูลที่หายไป ตอบถูกก็ได้คะแนน
> 
> ทั้งสองแบบน่าจะต้องทำให้โปรแกรมมีการเจนภาพdiagramจากโจทย์ด้วยตัวเองได้ด้วย

อันนี้ไม่แน่ใจว่าจารย์จะคิดว่าง่ายไปรึป่าวอะ

**Comment by nnrwp** [comment]
Bingo

**Comment by MindIssawara** [comment]
พวกแก้เกมแบบซูโดกุไรงี้ ไม่ก็หมากรุก?

**Comment by penpizza** [comment]
[หัวข้อโปรเจค เพิ่มเติม.pdf](https://github.com/MindIssawara/Cpp-Project/files/10712778/default.pdf)

**Comment by MindIssawara** [comment]
สรุปได้หัวข้อ LUDO
