### ISSUE TITLE
บัค แหกโค้ง (หมากเลยโค้ง)

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#10]

**Comment by penpizza** [comment]
- แก้แหกโค้งหมากสีแดงโดยการใส่ else if จะได้ไม่เข้าเงื่อนไขหลายเงื่อไขพร้อมกัน

**Comment by ApichayaUWU** [comment]
แก้ให้สีเขียวกับฟ้าแล้ว pushลงแล้ว
