### ISSUE TITLE
แก้เงื่อนไขเช็คเลนเส้นชัย

### ISSUE THREAD

**Issue by penpizza** [MindIssawara/Cpp-Project#12]

**Comment by ApichayaUWU** [comment]
if(x == 725 && y >= 100 && y <= 350)
    {
        if(d == (400 -y )/w)
        {
            x = 725;
            y = 400;
            Finished =1;
            timeToRoll =1;
            return 1;
        }else {
            Finished =1;
            timeToRoll =1;
            return 0;
        }
    }
