### ISSUE TITLE
บัคซ่อนกันแล้วบางสีจะกดไม่ไป

### ISSUE THREAD

**Issue by PAWEENNUTpuyfai** [MindIssawara/Cpp-Project#13]
แต่คือจริงๆแล้วยังไงก็ต้องไล่ตัวที่โดนทับกลับไปเพราะงั้นมันถือเป็นบัคไหมนะ

**Comment by MindIssawara** [comment]
ต้องลองทำโค้ดไล่กลับไปก่อน ไอ้ที่กดนี่ว่ามันแบบserchเจอสีอื่นก่อนละมันรีเทิร์นสีนั้นเลยมันเลยไม่ได้เดิา
