### ISSUE TITLE
function find_enemy 

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#16]
รายงานความคืบหน้าว่าไปถึงไหนแล้ว ไปใส่โค้ดใน find_enemy.h

**Comment by MindIssawara** [comment]
@nnrwp @l3eluGA ทำถึงไหนแล้ว ไม่เห็นอัพเดตความคืบหน้าเลย ภายในวันที่4เราจะได้งานใช่มั้ย

**Comment by l3eluGA** [comment]
ตอนนี้เราคิดกันบ้างแล้วแต่มีติดบ้าง เดียวพรุ่งนี้(3/3/2566)ขอปรึกษาหน้างานหน่อยได้ไหม

**Comment by PAWEENNUTpuyfai** [comment]
@nnrwp  @l3eluGA  เวลาที่หมากทับกัน หมากที่เป็นคนทับต้องไล่หมากที่ถูกทับกลับไปแต่ว่าของพวกแกที่เราเอาไปรันดูหมากที่ทับเป็ฯตัวโดนไล่ไปอยู่ในจุดเกิดหมากที่ถูฏทับ ตัวอย่างเช่น แดงทับเขียวแล้วแดงเข้าไปอยู่ในจุดเกิดของเขียว

**Comment by PAWEENNUTpuyfai** [comment]
@nnrwp @l3eluGA ของแกโอเคแล้วแหละเดี๋ยวที่เหลือเราแก้ให้โค้ดมันออกมาเป็นตระกะมากกว่านี้เอง

**Comment by PAWEENNUTpuyfai** [comment]
แก้ลูปในfind_enemyให้น้อยลงโดยการใช้การหาศตรูร่วมกับฟังก์ชั่นsearchที่มีอยู่แล้วมาปรับเปลี่ยนให้ใช้งานด้วยกันได้จึงเปลี่ยนชื่อฟังก์ชั่นเป็นchase_back
