### ISSUE TITLE
#image2 รูปภาพเพิ่มเติม+แก้ไข

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#17]
- ถ้ารูปแก้ขอ pixel เท่าเดิม
- ถ้าลูกเต๋าที่ใช้อยู่คือ158x158 เอามาต่อกัน มันจะ 948x158
![dice](https://user-images.githubusercontent.com/110963945/221564140-bed7bf7d-552d-4ec9-92a3-c382d6cfaa42.png)
- กรอบรอบลูกเต๋า 204x216 เอามาต่อกัน มันจะ 1020x216
![frame_dice](https://user-images.githubusercontent.com/110963945/221563761-df540f6b-efec-4f29-a9c4-26476c522783.png)
 
ใส่รูปใต้issueนี้ หรือไปcommitในโฟลด์เดอร์imageตรงโค้ด

**Comment by l3eluGA** [comment]
-ขอแก้รูปพื้นหลัง
![back1](https://user-images.githubusercontent.com/110966223/222457496-4819a34f-9cec-49d4-a5f7-56250ce3dbef.png)

**Comment by MindIssawara** [comment]
แบบเดิมสวยกว่ารึป่าว ความเห็นส่วนตัวนะ คนอื่นว่าไง

**Comment by l3eluGA** [comment]
อ๋าา งั้นเราว่าให้เพื่อนๆมาโหวตมั้ยๆ
เดียวเรามีเพิ่มอีกรูปด้วย

**Comment by l3eluGA** [comment]
![back2](https://user-images.githubusercontent.com/110966223/222458297-55b80049-6880-4b43-af02-94b535d1dbfb.png)

**Comment by MindIssawara** [comment]
ไว้โหวตกัน อันล่างสุดเราว่าอันก่อนหน้าดีกว่านะ

**Comment by l3eluGA** [comment]
อะเคร รับทราบ

**Comment by PAWEENNUTpuyfai** [comment]
เราว่าแบบเดิมอันแรกที่ใช้อยู่ปัจจุบันดีกว่า

**Comment by MindIssawara** [comment]
เดี๋ยวฟ้ากับฟิมช่วยทำรูปเพิ่มเติมน้า

**Comment by MindIssawara** [comment]
- หมากซ้อนกัน แบบเอารูปมาต่อกันแบบลูกเต๋าอะ มีอันเดียว  ซ้อน2 อัน 3...4...
- รูปที่จะเด้งขึ้นมาเวลาสีใดสีนึงชนะ
(ขอ 2 อันบนก่อน ภายในอาทิตย์นี้)
- หน้าเมนู พวกปุ่ม start/how to / exit
- หน้า how to

**Comment by l3eluGA** [comment]
![manu](https://user-images.githubusercontent.com/110966223/223735889-bdfed88d-607e-4c16-8564-3b325cd3dfd5.png)
![manu1](https://user-images.githubusercontent.com/110966223/223735904-e5a09810-1255-4a67-8389-661ea773c0c0.png)
พิกัด ปุ่ม
-start x:1045 y:354
-how to x:1020 y:507
-exit x:1045 y:660

**Comment by l3eluGA** [comment]
![start](https://user-images.githubusercontent.com/110966223/223737044-d910426d-3cef-4d29-b20d-b1e414bc08c4.png)
![how to](https://user-images.githubusercontent.com/110966223/223737055-7d44b207-7a79-4853-9a86-79a0fd835c5b.png)
![exit](https://user-images.githubusercontent.com/110966223/223737063-efba9a3e-1f10-4c78-ab99-c958d6abb4b0.png)
ขนาด ปุ่ม
-start ขนาด 250*100 px
-how to ขนาด 350*100 px
-exit ขนาด 250*100 px

**Comment by MindIssawara** [comment]
> ![manu](https://user-images.githubusercontent.com/110966223/223735889-bdfed88d-607e-4c16-8564-3b325cd3dfd5.png) ![manu1](https://user-images.githubusercontent.com/110966223/223735904-e5a09810-1255-4a67-8389-661ea773c0c0.png) พิกัด ปุ่ม -start x:1045 y:354 -how to x:1020 y:507 -exit x:1045 y:660

ไม่มีพื้นหลังเปล่าๆหรอ

**Comment by l3eluGA** [comment]
![cursor](https://user-images.githubusercontent.com/110966223/223743410-0aa4e986-75e5-4cf3-9803-5a2b36e877c5.png)
cursor ขนาด 30*30 px

**Comment by l3eluGA** [comment]
![cursor](https://user-images.githubusercontent.com/110966223/223756784-6365690a-8ad3-427a-81e9-6b22d1866d30.png)
cursor ขนาด 50*50 px

**Comment by penpizza** [comment]
![rรวม](https://user-images.githubusercontent.com/110964198/224067483-4f88a431-9d8f-4cb9-86ca-46b7c091de15.png)
![yรวม](https://user-images.githubusercontent.com/110964198/224067498-4d78a8ba-7b52-4244-9bb7-09be3e8b008f.png)
![bรวม](https://user-images.githubusercontent.com/110964198/224067506-e6b192a6-f1ed-41f0-8548-11ba670d8391.png)
![g](https://user-images.githubusercontent.com/110964198/224067512-d12deff1-bf9a-496b-876b-740fe67e5dbb.png)
หมากซ้อนกันทั้ง 4 สี ขนาด 200*50 px

**Comment by ApichayaUWU** [comment]
![Red1](https://user-images.githubusercontent.com/110961569/224132472-818b7c15-8684-4be2-97ca-9223dd0bd6a3.png)
![Yellow1](https://user-images.githubusercontent.com/110961569/224132525-1583dffc-11c3-42c0-ac1a-f7c68b3faa75.png)
![Blue1](https://user-images.githubusercontent.com/110961569/224132559-4fd3693d-4cbc-4200-8334-355f969fc2f5.png)
![Green1](https://user-images.githubusercontent.com/110961569/224132576-01a229d2-1e59-4775-843f-f1969f4ede6b.png)

**Comment by MindIssawara** [comment]
winG.png
winY.png
winB.png
winR.png

@ApichayaUWU

**Comment by ApichayaUWU** [comment]
![winB](https://user-images.githubusercontent.com/110961569/224235712-a93da1f5-f724-4643-9a8a-ea7db7a26553.png)
![winG](https://user-images.githubusercontent.com/110961569/224235717-55e9cbdc-a416-4f35-ac8c-f276d23abb59.png)
![winY](https://user-images.githubusercontent.com/110961569/224235739-80d7d038-cdb0-47a6-aba7-b8008567c1d9.png)
![winR](https://user-images.githubusercontent.com/110961569/224235774-e1de92a4-3df2-4993-aeec-6440c7e2bb9d.png)

**Comment by MindIssawara** [comment]
- ปุ่มแบบกลมๆ80x80pix ปุ่มโฮม ปุ่มรีเซต ปุ่มปิดเปิดเสียง(เอามาต่อกัน 2 ปุ่ม 80x160pix)

**Comment by nnrwp** [comment]
How to play (1500*900)
![How to play (2)](https://user-images.githubusercontent.com/110955515/224463967-433ea6ac-91ca-40a8-a755-eb7c7fa14743.png)

Back home (225*150) วางประมาณ (x,y)=(1200,725)
![Back to home page 225-150](https://user-images.githubusercontent.com/110955515/224464032-b15318bd-f49d-467c-8f2a-e8bc0f294fb8.png)

**Comment by penpizza** [comment]
home + background
![background](https://user-images.githubusercontent.com/110964198/224481962-22b9baad-4f4e-40e5-bcf8-3ac443ed4a2d.png)
![home](https://user-images.githubusercontent.com/110964198/224481966-b9a9301d-b6ab-49e1-8b31-22b38c86b109.png)
พิกัด
![พิกัดปก](https://user-images.githubusercontent.com/110964198/224481982-59d24206-b169-4cbc-a867-700e16030619.jpg)
![พิกัดกระดาน](https://user-images.githubusercontent.com/110964198/224481983-7b224fb9-2b59-402c-a849-e5d3d5abfbe2.jpg)

**Comment by penpizza** [comment]
ปุ่มต่างๆ
![onoff](https://user-images.githubusercontent.com/110964198/224482003-c20497a3-3ee2-4c83-91dc-63a87c5580ce.png)
![start](https://user-images.githubusercontent.com/110964198/224482005-11b7f62d-e3d3-4ef5-92ab-ae0c224ce742.png)
![exit](https://user-images.githubusercontent.com/110964198/224482006-46f6ee28-cf1e-44fa-9b7f-99b90e9643cc.png)
![HowTo](https://user-images.githubusercontent.com/110964198/224482008-eb675df9-19e1-4ade-be4f-d51c789c7cfd.png)

**Comment by ApichayaUWU** [comment]
![NG](https://user-images.githubusercontent.com/110961569/224482270-cccbf587-bfe8-448e-a948-b75067d4f2e4.png)
NG full size 1500*900 px
![NGfit](https://user-images.githubusercontent.com/110961569/224482329-15c9ca77-1f97-40b3-8a7e-4f59d2cc84e9.png)
ปุ่มnew gameที่วางอยู่ในภาพขนาด1500*900 px

**Comment by penpizza** [comment]
ปุ่ม home+reset
![homegamepage](https://user-images.githubusercontent.com/110964198/224507322-b53b1c9d-7f57-4262-a58e-2d27cfd8e2f0.png)
![reset](https://user-images.githubusercontent.com/110964198/224507323-796e47e5-ebc0-462e-adba-06d03d80e574.png)
พิกัดหน้าเกม
![พิกัดกระดาน](https://user-images.githubusercontent.com/110964198/224507364-0d251f87-cbb0-458d-8ded-3c5a00e712ea.jpg)

**Comment by nnrwp** [comment]
![HowToPage1](https://user-images.githubusercontent.com/110955515/225201822-82f027ec-f51c-4ae5-be07-b2dc8d03a834.png)

**Comment by nnrwp** [comment]
![How to play](https://user-images.githubusercontent.com/110955515/225212501-fb3a5bed-b720-44f8-a1e4-42796d18265b.png)

**Comment by l3eluGA** [comment]
![frame](https://user-images.githubusercontent.com/110966223/225229836-fcff6b00-22f4-4b80-8462-b5cc11f44810.png)

**Comment by PAWEENNUTpuyfai** [comment]
มันต่างจากอันเดิมตรงไหนเหรอ??

**Comment by ApichayaUWU** [comment]
![homebot](https://user-images.githubusercontent.com/110961569/225230205-394a7013-265d-44c3-8105-98f5fe2b37f9.png)
![IMG_2778 2](https://user-images.githubusercontent.com/110961569/225230551-5f7792d3-ac7d-4c99-ae83-9f96c59290b7.jpg)
ปุ่มโฮม ขนาด 368 x 130 px วางที่พิกัด (1099,758)

**Comment by nnrwp** [comment]
![all](https://user-images.githubusercontent.com/110955515/225507838-71ab51e4-e164-4e89-bda4-18fbdbe3024e.png)
