### ISSUE TITLE
ทุกคนมาช่วยรวมความคิดเขียนHow to หน่อยย

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#22]
นี่คิดภาพรวมไม่ออกอะ ลองช่วยๆกันเขียนพวกกติกาเล็กน้อยออกมาได้มั้ย จริงๆจะได้เช็คด้วยว่าขาดฟังก์ชั่นอะไรมั้ยอะ 

ตอนนี้ได้เป็น
- มีผู้เล่นสี่คน เริ่มที่สีเขียวเสมอ โดยจะผลัดกันทอยเต๋า หากใครทอยได้ 6 ก่อน จะได้เลือกหมากออกจากฐานก่อน ผู้เล่นคนเดิมทอยอีกรอบเผื่อได้หมากเดินไปกี่ช่องตามที่ทอยได้
- ถ้าทอยได้ แต้มเท่าไหร่เดินตามนั้น แต่ถ้าได้ 6 ทอยซ้ำได้อีกรอบ หรือจะเอาหมากออกมาเดินก็ได้
- พาหมากเดินตามทางจนถึงเส้นชัยครบสี่ตัว เป็นผู้ชนะ
- ถ้าหมากตัวเองไปทับหมากสีอื่นขณะเดินบนกระดาน ไล่สีอื่นกลับ

ช่วยกันลิสหน่อยฮะะ

**Comment by PAWEENNUTpuyfai** [comment]
-ถ้าทอยหมากได้เกินจำนวนช่องการเดินไปถึงเส้นชัยหากกดหมากนั้นจะเสียรอบนั้นดดยที่หมากไม่เดิน
-การเลือกเดินหมากหากมีหมากอยู่ในกระดานจะเลือกเดินตัวไหนก่อนก็ได้

**Comment by penpizza** [comment]
ขอเพิ่มจากปุยฝ้ายนิดนึง - ดังนั้นถ้าเข้าเลนเส้นชัยขอแต่ละสี ต้องทอยแต้มเต๋าให้เท่ากับช่องที่เหลือ 
นอกนั้นก็ครบแล้วนะะะ

**Comment by ApichayaUWU** [comment]
+ หมากสีเดียวกันสามารถยืนซ้อนกันในช่องเดียวกันได้ แต่เมื่อเจอสีอื่น สีที่อยู่ก่อนจะถูกส่งกลับไปที่จุดเริ่มต้น

**Comment by PAWEENNUTpuyfai** [comment]
ลูกเต๋าสีแดงแปลว่าactiveสามารถกดเล่นได้
ลูกเต๋าสีดำคือไม่มีตัวที่สามารถเดินได้บนกระดาน
