### ISSUE TITLE
บัค pick 

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#25]
เวลาหมากเข้าเส้นชัยแล้ว/โดนไล่กลับจนไม่เหลือหมากบนกระดาน ทอยเต๋าต่อไม่ได้

**Comment by PAWEENNUTpuyfai** [comment]
เข้าเส้นชัย โดนไล่กลับ สิ่งทีทำให้หมากไม่มีในบนกระดานจะกดลูกเต๋าข้ามตาได้เลยแล้ว แก้บัคเรียบร้อย
โดยเปลี่ยน pickจาก boolเป็น int นับจำนวนหมากบนกระดานแทน
