### ISSUE TITLE
Tester's codes

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#29]
โกงเกมกันเถอะฮะ  เทสไม่ไหวแล้ว

**Comment by MindIssawara** [comment]
พาหมากตัวที่1ไปชนะ

if (event.key.code == Keyboard::Down) {
            if (Round == 1) {
                green[0][0] = 425;
                green[0][1] = 400;
                win[0] = move_green(green[0][0], green[0][1], 55);
                win[0] = move_green(green[0][0], green[0][1], 1);
                cout << win[0];
            }
            if (Round == 2) {
                yellow[0][0] = 775;
                yellow[0][1] = 150;
                win[1]=move_yellow(yellow[0][0], yellow[0][1], 56);
                cout << win[1];
            }
            if (Round == 3) {
                blue[0][0] = 1025;
                blue[0][1] = 500;
                win[2] = move_blue(blue[0][0], blue[0][1], 55);
                win[2] = move_blue(blue[0][0], blue[0][1], 1);
                cout << win[2];
            }
            if (Round == 4) {
                red[0][0] = 675;
                red[0][1] = 750;
                win[3] = move_red(red[0][0], red[0][1], 56);
                cout << win[3];
            }
            Finished = 1;
            timeToRoll = 1;
        }//unused for now

**Comment by PAWEENNUTpuyfai** [comment]
หมากไปอยู๋หน้าเส้นชัย

if (event.key.code == Keyboard::Left) {
            green[0][0] = 375, green[0][1] = 450;
            yellow[0][0] = 725, yellow[0][1] = 100;
            blue[0][0] = 1075, blue[0][1] = 450;
            red[0][0] = 725, red[0][1] = 800;
            pick[0] = 1, pick[1] = 1, pick[2] = 1, pick[3] = 1;
            cout << pick[0] << pick[1] << pick[2] << pick[3];
        }

**Comment by MindIssawara** [comment]
ชนะ4

if (event.key.code == Keyboard::Down) {
            if (Round == 1) {
                win[0] = 4;
            }
            if (Round == 2) {
                win[1] = 4;
            }
            if (Round == 3) {
                win[2] = 4;
            }
            if (Round == 4) {
                win[3] = 4;
            }
            Finished = 1;
            timeToRoll = 1;
        }//unused for now
