### ISSUE TITLE
ลองทำ GUI ดูว่าทำได้มั้ย 

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#3]
อยากลองดูว่าพอทำได้มั้ย ถ้าทำได้โปรเจคน่าจะไปได้กว้างขึ้น

**Comment by PAWEENNUTpuyfai** [comment]
https://youtube.com/watch?v=zH_omFPqMO4&feature=shares

**Comment by PAWEENNUTpuyfai** [comment]
https://www.sfml-dev.org/tutorials/2.5/start-vc.php

**Comment by MindIssawara** [comment]
![image](https://user-images.githubusercontent.com/110963945/218122901-dd6a59e0-1a43-4f8a-b091-ebafca3e94f1.png)
บัคอะไรกันนะ

**Comment by PAWEENNUTpuyfai** [comment]
> 

นั้นสิอยากจะรู้เหมือนกัน
https://stackoverflow.com/questions/53610481/how-to-solve-cc-linkobj-o-bin-libs
![Screenshot 2023-02-10 220225](https://user-images.githubusercontent.com/110964154/218124474-fe03a443-a658-4c32-a953-8dac3fe99bef.png)
เขาว่ามางั้นแต่มันต้องแก้ตรงไหนบ้างนิ

**Comment by MindIssawara** [comment]
> 

scanf มันภาษาc ไม่ใช่c++ ละก็ไม่มีscanในโค้ดสักตัว

**Comment by PAWEENNUTpuyfai** [comment]
> > 
> 
> scanf มันภาษาc ไม่ใช่c++ ละก็ไม่มีscanในโค้ดสักตัว

ไม่รู้ด้วยซ้ำว่ามันผิดอะไรนั้นไม่ใช่โค้ดที่เอามาลองเขียนด้วยซ้ำแต่เป็นโค้ดของcomplyerแล้วมั้งนั้นมันไม่ได้ผิดที่เราแล้ววววววววววววว

**Comment by MindIssawara** [comment]
![image](https://user-images.githubusercontent.com/110963945/218154999-aabd6bdb-2a22-4c8d-910b-1dd9a0c903a0.png)
![image](https://user-images.githubusercontent.com/110963945/218155154-36f4f2cd-f990-4aae-9f4d-695c26eb4958.png)
![image](https://user-images.githubusercontent.com/110963945/218155215-c2010810-12fb-42e5-89fe-9e7f5dcac199.png)
![image](https://user-images.githubusercontent.com/110963945/218155317-1fc0abc2-316b-4e0a-96e7-09b4351d7ced.png)
![image](https://user-images.githubusercontent.com/110963945/218155363-6d720318-48f3-4761-a55e-bcb386da1296.png)
sfml-window-s-d.lib
sfml-graphics-s-d.lib
sfml-audio-s-d.lib
sfml-network-s-d.lib
sfml-system-s-d.lib
sfml-main-d.lib
opengl32.lib
winmm.lib
gdi32.lib
jpeg.lib
freetype.lib
openal32.lib
flac.lib
vorbisenc.lib
vorbisfile.lib
vorbis.lib
ogg.lib
ws2_32.lib

**Comment by MindIssawara** [comment]
บัค LNK1104 ยังไม่รู้แก้ไง

**Comment by MindIssawara** [comment]
![image](https://user-images.githubusercontent.com/110963945/218235268-7fb8f9a2-49a6-4507-b61f-3d2a2b7247fc.png)
น้องมาละ

**Comment by MindIssawara** [comment]
![image](https://user-images.githubusercontent.com/110963945/218236036-ea24771d-b0a5-4486-80a6-3c3df4190aa7.png)

**Comment by MindIssawara** [comment]
ทำได้ละมั้ง
