### ISSUE TITLE
ทำสไลด์

### ISSUE THREAD

**Issue by MindIssawara** [MindIssawara/Cpp-Project#32]

**Comment by PAWEENNUTpuyfai** [comment]
![image](https://user-images.githubusercontent.com/110964154/225086399-addb446b-9042-4c5b-84db-c6cb8a4f44a2.png)
![image](https://user-images.githubusercontent.com/110964154/225086503-fac32dac-c7a7-4436-a34d-5b62cf2fe4bf.png)

**Comment by PAWEENNUTpuyfai** [comment]
![image](https://user-images.githubusercontent.com/110964154/225086672-078c7d86-fad0-4e6d-beab-c33900b6e34e.png)
![image](https://user-images.githubusercontent.com/110964154/225086757-7f2f2030-ed05-4a12-abae-e74a3d6f4ddc.png)

**Comment by PAWEENNUTpuyfai** [comment]
![image](https://user-images.githubusercontent.com/110964154/225087245-977a236b-2009-4a6c-87e1-fb0af38d786b.png)
![image](https://user-images.githubusercontent.com/110964154/225087331-82ff4885-fd17-4dc8-9230-35dad59bdd06.png)

**Comment by PAWEENNUTpuyfai** [comment]
![image](https://user-images.githubusercontent.com/110964154/225089824-736ecb90-15f6-43f7-b85c-2fc52a38b5bf.png)
![image](https://user-images.githubusercontent.com/110964154/225089897-4a3a859c-68c1-436a-8611-fbc1845efb78.png)

**Comment by PAWEENNUTpuyfai** [comment]
![image](https://user-images.githubusercontent.com/110964154/225090010-2ff16a8e-640b-4443-a7fa-95578c7305db.png)
![image](https://user-images.githubusercontent.com/110964154/225090210-7bea810e-8e7d-410f-874e-aed809a1613f.png)

**Comment by MindIssawara** [comment]
![1678859692608](https://user-images.githubusercontent.com/110963945/225219618-b69673fd-24c4-4a9c-a85a-6c73b2608298.jpg)
![1678859695258](https://user-images.githubusercontent.com/110963945/225219646-2e2401d2-a2a8-4654-b1de-a5e4166a4c72.jpg)

**Comment by MindIssawara** [comment]
บัคในdev c++ ไม่ทราบที่มา
![218122901-dd6a59e0-1a43-4f8a-b091-ebafca3e94f1](https://user-images.githubusercontent.com/110963945/225219873-191671ce-c849-4115-9161-b6b40a2bdd2b.png)

**Comment by MindIssawara** [comment]
![image](https://user-images.githubusercontent.com/110963945/225248217-b34cd7cf-ef48-4447-96b2-fd36fa7e93af.png)
หน้า how to

**Comment by MindIssawara** [comment]
![image](https://user-images.githubusercontent.com/110963945/225248900-6ff0ca1b-46ac-4132-8f61-0edceb2315e4.png)
![image](https://user-images.githubusercontent.com/110963945/225249293-cd5a0390-ad3e-43f0-8b23-5c6fbd9cd497.png)
![image](https://user-images.githubusercontent.com/110963945/225249505-c7b5d25c-38df-4e47-a77f-b19edbb0385e.png)
![image](https://user-images.githubusercontent.com/110963945/225249743-2b344def-b20b-4276-bb4d-fbfd54d614ea.png)
หน้าชนะ

**Comment by penpizza** [comment]
https://www.canva.com/design/DAFdQELQ6IY/sD3ZZVeh5c3YV0WIoC48iQ/view?utm_content=DAFdQELQ6IY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
ฝากตรวจความถูกต้อง + เรียบร้อยด้วยนะค้าบบบ
