### ISSUE TITLE
image#1

### ISSUE THREAD

**Issue by PAWEENNUTpuyfai** [MindIssawara/Cpp-Project#6]

**Comment by l3eluGA** [comment]
![1](https://user-images.githubusercontent.com/110966223/219658278-b7e658fe-0a59-4324-a37d-63c35d0d969c.jpg)

**Comment by l3eluGA** [comment]
![2](https://user-images.githubusercontent.com/110966223/219658550-4fae7c6c-0657-4743-8ef9-304d939efef4.jpg)

**Comment by nnrwp** [comment]
![IMG_0697](https://user-images.githubusercontent.com/110955515/219830264-f726465c-5944-4d6e-8023-94526e4e703a.jpeg)

**Comment by MindIssawara** [comment]
- Backgroudกับกระดานมันควรซ้อนเป็นรูปเดียวนะ พิกัดที่มาร์คมาที่แกลงในgitอะมันเป็นพิกัดบน750×750 ไม่ใช่พิกัดรวมอะ สมมุติแกทำแบล็คกราวมา900×1500  พิกัดที่เราใช้คือพิกัดบน900×1500อะ
- พิกัดที่เราใช้เขียนโปรแกรมเป็นพิกัดมุมซ้ายบนของรูปอะ ขอเป็นจุดตัดตารางแทนจุดตรงกลางของแต่ละช่องได้มั้ย
![1676826924029](https://user-images.githubusercontent.com/110963945/219963705-9bb57e5b-2498-461a-bf7e-24c98509b699.jpg)
ประมาณจุดสีเหลือง
- ทำรูปหมาก 4 สี กับเต๋า 6 ด้านรึยัง

**เราขอรูปทั้งหมดไว้ภายในวันจันทร์คือวันนี้นะ ทำทันใช่มั้ย

**Comment by nnrwp** [comment]
> - Backgroudกับกระดานมันควรซ้อนเป็นรูปเดียวนะ พิกัดที่มาร์คมาที่แกส่งมามันเป็นพิกัดบน750×750 ไม่ใช่พิกัดรวมอะ สมมุติแกทำแบล็คกราวมา900×1500  พิกัดที่เราใช้คือพิกัดบน900×1500อะ
> 
> - พิกัดที่เราใช้เขียนโปรแกรมเป็นพิกัดมุมซ้ายบนของรูปอะ ขอเป็นจุดตัดตารางแทนจุดตรงกลางของแต่ละช่องได้มั้ย
> 
> ![1676826924029](https://user-images.githubusercontent.com/110963945/219963705-9bb57e5b-2498-461a-bf7e-24c98509b699.jpg)
> 
> ประมาณจุดสีเหลือง
> 
> - ทำรูปหมาก 4 สี กับเต๋า 6 ด้านรึยัง
> 
> 
> 
> **เราขอรูปทั้งหมดไว้ภายในวันจันทร์คือวันนี้นะ ทำทันใช่มั้ย

กำลังดำเนินการ🫡

**Comment by nnrwp** [comment]
![หมากเขียว](https://user-images.githubusercontent.com/110955515/219966683-be3acbfd-3fa4-44be-a02c-93a2855c276b.png)
![หมากแดง](https://user-images.githubusercontent.com/110955515/219966687-2874dede-4b64-415b-9423-1441539a16aa.png)
![หมากน้ำเงิน](https://user-images.githubusercontent.com/110955515/219966688-6ecd65fd-8b73-44dc-bd6b-f816201060e8.png)
![หมากเหลือง](https://user-images.githubusercontent.com/110955515/219966690-f24a74ce-ee7a-40ff-b50b-e8345737a603.png)

**Comment by nnrwp** [comment]
![image](https://user-images.githubusercontent.com/110955515/219968819-70f4b032-17d0-46c5-a8b0-aee050de4d09.jpeg)
พิกัด รูปเต็มรอใส่ลูกศรเน่อ

**Comment by MindIssawara** [comment]
> ![หมากเขียว](https://user-images.githubusercontent.com/110955515/219966683-be3acbfd-3fa4-44be-a02c-93a2855c276b.png) ![หมากแดง](https://user-images.githubusercontent.com/110955515/219966687-2874dede-4b64-415b-9423-1441539a16aa.png) ![หมากน้ำเงิน](https://user-images.githubusercontent.com/110955515/219966688-6ecd65fd-8b73-44dc-bd6b-f816201060e8.png) ![หมากเหลือง](https://user-images.githubusercontent.com/110955515/219966690-f24a74ce-ee7a-40ff-b50b-e8345737a603.png)

รูปหมากเราเปิดไม่ได้

**Comment by nnrwp** [comment]
> > ![หมากเขียว](https://user-images.githubusercontent.com/110955515/219966683-be3acbfd-3fa4-44be-a02c-93a2855c276b.png) ![หมากแดง](https://user-images.githubusercontent.com/110955515/219966687-2874dede-4b64-415b-9423-1441539a16aa.png) ![หมากน้ำเงิน](https://user-images.githubusercontent.com/110955515/219966688-6ecd65fd-8b73-44dc-bd6b-f816201060e8.png) ![หมากเหลือง](https://user-images.githubusercontent.com/110955515/219966690-f24a74ce-ee7a-40ff-b50b-e8345737a603.png)
> 
> 
> 
> รูปหมากเราเปิดไม่ได้

ลองเปิดในโน้ตบุ๊คดูยังอะ

**Comment by nnrwp** [comment]
![หมากเหลือง](https://user-images.githubusercontent.com/110955515/220066104-5b9040dc-3682-4dbf-b553-fdbb6c34aa27.png)
![BG + ตาราง](https://user-images.githubusercontent.com/110955515/220066117-8ede28a7-f0b5-41cc-bc0e-eb434b18012c.png)
![หมากเขียว](https://user-images.githubusercontent.com/110955515/220066146-a7028393-32b2-436f-a5a3-823dabf7bdf2.png)
![หมากแดง](https://user-images.githubusercontent.com/110955515/220066154-92b517b1-354c-4e15-b2c0-c2c408f2b8dc.png)
![หมากน้ำเงิน](https://user-images.githubusercontent.com/110955515/220066163-be6365b9-e260-4fa9-991a-661e833d4713.png)

**Comment by l3eluGA** [comment]
![dice3](https://user-images.githubusercontent.com/110966223/220067277-3b44adfd-1e5c-4c9f-a953-e4a2ef656804.png)
![dice4](https://user-images.githubusercontent.com/110966223/220067283-276a54e7-cc70-4c44-a934-aff02e2c794a.png)
![dice5](https://user-images.githubusercontent.com/110966223/220067284-974009f1-4ff2-4d04-9eb9-a9258cf159ee.png)
![dice6](https://user-images.githubusercontent.com/110966223/220067288-b85274da-1ed9-4d11-9aaa-fe2dc45cda5d.png)
![dice1](https://user-images.githubusercontent.com/110966223/220067294-2fb4dd44-39dd-425a-94ad-7cc6ee0e755e.png)
![dice2](https://user-images.githubusercontent.com/110966223/220067299-2dff0554-2abe-42ac-ba7c-910aa250049e.png)

**Comment by nnrwp** [comment]
![BG + ตาราง](https://user-images.githubusercontent.com/110955515/220069453-718b5251-bc4f-4174-b7a2-658918f1756a.png)

**Comment by PAWEENNUTpuyfai** [comment]
> ![dice3](https://user-images.githubusercontent.com/110966223/220067277-3b44adfd-1e5c-4c9f-a953-e4a2ef656804.png)
> ![dice4](https://user-images.githubusercontent.com/110966223/220067283-276a54e7-cc70-4c44-a934-aff02e2c794a.png)
> ![dice5](https://user-images.githubusercontent.com/110966223/220067284-974009f1-4ff2-4d04-9eb9-a9258cf159ee.png)
> ![dice6](https://user-images.githubusercontent.com/110966223/220067288-b85274da-1ed9-4d11-9aaa-fe2dc45cda5d.png)
> ![dice1](https://user-images.githubusercontent.com/110966223/220067294-2fb4dd44-39dd-425a-94ad-7cc6ee0e755e.png)
> ![dice2](https://user-images.githubusercontent.com/110966223/220067299-2dff0554-2abe-42ac-ba7c-910aa250049e.png)

![5FA270EC-7C2B-40FA-B60F-EAA26CCC79C9](https://user-images.githubusercontent.com/110964154/220083354-67e01d89-bf60-40aa-993b-431770001d86.jpeg)
ลูกเต๋าเอาที่เป็น6ด้านต่อกันด้วยอีก 1 รูปนะ

**Comment by l3eluGA** [comment]
![all dice](https://user-images.githubusercontent.com/110966223/220116859-d2676c23-8f03-4881-95bf-be5b852773c8.png)

**Comment by nnrwp** [comment]
![ลูกศรเขียว](https://user-images.githubusercontent.com/110955515/220124915-dcd37432-ebdd-41bd-86a8-aaf89eb2bab2.png)
![ลูกศรน้ำเงิน](https://user-images.githubusercontent.com/110955515/220124924-26b058f2-c6d9-45eb-ac21-f8135ca76411.png)
![ลูกศรแดง](https://user-images.githubusercontent.com/110955515/220124926-641c57d3-e734-4bec-807f-7f12de6166a0.png)
![ลูกศรเหลือง](https://user-images.githubusercontent.com/110955515/220124936-103ef0c9-58d5-4c44-8bf4-75e4340bb9d1.png)

**Comment by l3eluGA** [comment]
![all dice2](https://user-images.githubusercontent.com/110966223/220132166-e4862dd5-39e5-42bf-bd6d-981369c3151e.png)

**Comment by MindIssawara** [comment]
ปิด issue รูปรอบแรกนะ
