### ISSUE TITLE
function game

### ISSUE THREAD

**Issue by PAWEENNUTpuyfai** [MindIssawara/Cpp-Project#7]

**Comment by ApichayaUWU** [comment]
[https://github.com/MindIssawara/Cpp-Project/blob/main/function_random.h](url)

**Comment by ApichayaUWU** [comment]
`#include<iostream>
#include<time.h>
#include<cstdlib>
using namespace std;

int roll_dice()
{
    int d;
    d= rand() %6 +1;
    return d;
}`

**Comment by MindIssawara** [comment]
แกอยากให้พวกฟังก์ขั่นเดินเราส่งไรไปให้บ้างตอนเรียกใช้ แบบ void move(พิกัด x,พิกัด y,แต้มเต๋าที่ทอยได้,สีหมาก) เอาอะไรบ้าง เพิ่มตัวแปรไรมั้ย หรืออันไหนไม่เอา

**Comment by ApichayaUWU** [comment]
-พิกัด x,y
-แต้มเต๋า
-ค่าคงที่ แบบเดิน1ก้าวบนกระดานใช้ระยะทางเท่าไหร่ไรงี้ ตั้งเป็นglobal variable ไว้ก็ได้ เวลามาเปลี่ยนทีหลังจะได้ทำได้ง่ายๆ
ปล.อาจจะมีเพิ่มมาทีหลังอีก ต้องลองเขียนฟังชันออกมาก่อน

**Comment by penpizza** [comment]
ฟังก์ชันเดินหมากสีแดง
void move_red (int &x,int &y,int d){
    for (int i=0; i<d; i++){
        if(x == 675 && y>=600 && y<=800) y-=50;
        if(x == 675 && y==550) {
            x=625;
            y=500;
            }
        if(y == 500 && x>=425 && x<=625) x-=50;
        if(x == 375 && y>=450 && y<=500) y-=50;
        if(y == 400 && x>=375 && x<=515) x+=50;
        if(x == 625 && y==400) {
            x=675;
            y=350;
            }
        if(x == 675 && y>=150 && y<=350) y-=50;
        if(y == 100 && x>=675 && x<=725) x+=50;
        if(x == 775 && y>=100 && y<=300) y+=50;
        if(x == 775 && y==350) {
            x=825;
            y=400;
            }
        if(y == 400 && x>=825 && x<=1025) x+=50;
        if(x == 1075 && y>=400 && y<=450) x+=50;
        if(y == 500 && y>=875 && y<=1075) y-=50;
        if(x == 825 && y==500) {
            x=775;
            y=550;
            }
        if(x == 775 && y>=550 && y<=750) y+=50;
        if(y == 800 && x == 775) x-=50;
        if(x == 725 && y >= 550 && y<= 800) y-=50;
    }
}

**Comment by penpizza** [comment]
ไม่แน่ใจว่าช่วง x,y ถูกมั้ยนะ

**Comment by penpizza** [comment]
(ตรวจช่วงฟังก์ชันและแก้การเปลี่ยนค่า x,y แล้ว)
//function move สีแดง
void move_red (int &x,int &y,int d){
    for (int i=0; i<d; i++){
        if(x == 675 && y>=600 && y<=800) y-=50;
        if(x == 675 && y==550) {
            x=625;
            y=500;
            }
        if(y == 500 && x>=425 && x<=625) x-=50;
        if(x == 375 && y>=450 && y<=500) y-=50;
        if(y == 400 && x>=375 && x<=515) x+=50;
        if(x == 625 && y==400) {
            x=675;
            y=350;
            }
        if(x == 675 && y>=150 && y<=350) y-=50;
        if(y == 100 && x>=675 && x<=725) x+=50;
        if(x == 775 && y>=100 && y<=300) y+=50;
        if(x == 775 && y==350) {
            x=825;
            y=400;
            }
        if(y == 400 && x>=825 && x<=1025) x+=50;
        if(x == 1075 && y>=400 && y<=450) y+=50;
        if(y == 500 && y>=875 && y<=1075) x-=50;
        if(x == 825 && y==500) {
            x=775;
            y=550;
            }
        if(x == 775 && y>=550 && y<=750) y+=50;
        if(y == 800 && x == 775) x-=50;
        if(x == 725 && y >= 550 && y<= 800) y-=50;
    }
}
//function move สีเหลือง
void move_yellow (int &x,int &y,int d){
    for (int i=0; i<d; i++){
        if(x == 775 && y>=100 && y<=300) y+=50;
        if(x == 775 && y==350) {
            x=825;
            y=400;
            }
        if(y == 400 && x>=825 && y<=1025) x+=50;
        if(x == 1075 && y>=400 && y<=450) y+=50;
        if(y == 500 && y>=875 && y<=1075) x-=50;
        if(x == 825 && y==500) {
            x=775;
            y=550;
            }
        if(x == 775 && y>=550 && y<=750) y+=50;
        if(y == 800 && x>=725 && y<=775) x-=50;
        if(x == 675 && y>=600 && y<=800) y-=50;
        if(x == 675 && y==550) {
            x=625;
            y=500;
            }
        if(y == 500 && x>=425 && x<=625) x-=50;
        if(x == 375 && y>=450 && y<=500) y-=50;
        if(y == 400 && x>=375 && x<=515) x+=50;
        if(x == 625 && y==400) {
            x=675;
            y=350;
            }
        if(x == 675 && y>=150 && y<=350) y-=50;
        if(y == 100 && x==675 ) x+=50;
        if(x == 725 && y >= 100 && y<= 350) y+=50;

    }
}

**Comment by ApichayaUWU** [comment]
----> เดินหมากสีเขียว
void move_green(int &x,int &y,int dice){
    for(int i = 0; i < dice ; i++)
    {
        //formatทางตรงแกน x ทิศขวา --> if(x >= ต้น && x < ปลาย && y == คงที่)
        if(x >= 425 && x < 625 && y == 400) 
        {
            x = x + w;
        }
        //จุดกระโดด 1
        if(x == 625 && y == 400) 
        {
            x = 675;
            y = 350;
        }
        //formatทางตรงแกน y ทิศขึ้น --> if(y <= ต้น && y > ปลาย && x == คงที่)
        if( y <= 350 && y > 100 && x== 675 )
        {
            y = y - w;
        }
        if( x >= 675 && x < 775 && y == 100)
        {
            x = x+ w;
        }
        //formatทางตรงแกน y ทิศลง --> if(y >= ต้น && y < ปลาย && x == คงที่)
        if( y >= 100 && y < 350 && x== 775 )
        {
            y = y + w;
        }
        //จุดกระโดด 2
        if(x == 775 && y == 350) 
        {
            x = 825;
            y = 400;
        }
        if(x >= 825 && x < 1075 && y == 400) 
        {
            x = x + w;
        }
        if( y >= 400 && y < 500 && x== 1075 )
        {
            y = y + w;
        }
         //formatทางตรงแกน x ทิศซ้าย --> if(x <= ต้น && x > ปลาย && y == คงที่)
        if(x <= 1075 && x > 825 && y == 500) 
        {
            x = x - w;
        }
        //จุดกระโดด 3
        if(x == 825 && y == 500) 
        {
            x = 775;
            y = 550;
        }
        if( y >= 550 && y < 800 && x== 775 )
        {
            y = y + w;
        }
        if(x <= 775 && x > 675 && y == 800) 
        {
            x = x - w;
        }
        if( y <= 800 && y > 550 && x== 675 )
        {
            y = y - w;
        }
        //จุดกระโดด 4
        if(x == 675 && y == 550) 
        {
            x = 625;
            y = 500;
        }
        if(x <= 625 && x > 375 && y == 500) 
        {
            x = x - w;
        }
        if( y <= 500 && y > 450 && x== 375 )
        {
            y = y - w;
        }
        if(x >= 375 && x < 675 && y == 450) 
        {
            x = x + w;
        }
    }
}


----> เดินหมากสีฟ้า
void move_blue(int &x,int &y,int dice)
{
    for(int i = 0; i < dice ; i++)
    {
        if(x <= 1025 && x > 825 && y == 500) 
        {
            x = x - w;
        }
        if(x == 825 && y == 500) 
        {
            x = 775;
            y = 550;
        }
        if( y >= 550 && y < 800 && x== 775 )
        {
            y = y + w;
        }
        if(x <= 775 && x > 675 && y == 800) 
        {
            x = x - w;
        }
        if( y <= 800 && y > 550 && x== 675 )
        {
            y = y - w;
        }
        if(x == 675 && y == 550) 
        {
            x = 625;
            y = 500;
        }
        if(x <= 625 && x > 375 && y == 500) 
        {
            x = x - w;
        }
        if( y <= 500 && y > 400 && x== 375 )
        {
            y = y - w;
        }
        if(x >= 375 && x < 625 && y == 400) 
        {
            x = x + w;
        }
        if(x == 625 && y == 400) 
        {
            x = 675;
            y = 350;
        }
        if( y <= 350 && y > 100 && x== 675 )
        {
            y = y - w;
        }
        if( x >= 675 && x < 775 && y == 100)
        {
            x = x+ w;
        }
        if( y >= 100 && y < 350 && x== 775 )
        {
            y = y + w;
        }
        if(x == 775 && y == 350) 
        {
            x = 825;
            y = 400;
        }
        if(x >= 825 && x < 1075 && y == 400) 
        {
            x = x + w;
        }
        if( y >= 400 && y < 450 && x== 1075 )
        {
            y = y + w;
        }
        if(x <= 1075 && x > 775 && y == 450) 
        {
            x = x - w;
        }
    }
}

**Comment by ApichayaUWU** [comment]
ตอนนี้functionเดินธรรมดาน่าจะเสร็จแล้วทั้ง4สี เข้าไปดูในfile function_move.hในหน้าโค้ดได้เลย

**Comment by penpizza** [comment]
ฟังก์ชัน move เสร็จแล้ว หมากเดินทางธรรมดา+เลนเส้นชัยได้แล้ว
