### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by PAWEENNUTpuyfai** [MindIssawara/Cpp-Project#8]
- เรียกใช้ function จากฟิมกับฟ้า
- จัดการฟังก์ชั่น main 
- funtion ที่ใช้sfml

**Comment by PAWEENNUTpuyfai** [comment]
จุด start

int red[4][2] = { {450,625},{550,625},{450,725},{550,725} };
int green[4][2] = { {450,175},{550,175},{450,275},{550,275} };
int yellow[4][2] = { {900,175},{1000,175},{900,275}, {1000,275} };
int blue[4][2] = { {900,625},{1000,625},{900,725},{1000,725} };

**Comment by PAWEENNUTpuyfai** [comment]
g1(g) ,g2(g) , g3(g) , g4(g);
y1(y) , y2(y) , y3(y) , y4(y);

**Comment by MindIssawara** [comment]
r1.setPosition(red[0][0], red[0][1]);
        r2.setPosition(red[1][0], red[1][1]);
        r3.setPosition(red[2][0], red[2][1]);
        r4.setPosition(red[3][0], red[3][1]);
        b1.setPosition(x, y);
        b2.setPosition(x, y);
        b3.setPosition(x, y);
        b4.setPosition(x, y);
        g1.setPosition(x, y);
        g2.setPosition(x, y);
        g3.setPosition(x, y);
        g4.setPosition(x, y);
        y1.setPosition(x, y);
        y2.setPosition(x, y);
        y3.setPosition(x, y);
        y4.setPosition(x, y);

**Comment by PAWEENNUTpuyfai** [comment]
r1.setPosition(red[0][0], red[0][1]);
r2.setPosition(red[1][0], red[1][1]);
r3.setPosition(red[2][0], red[2][1]);
r4.setPosition(red[3][0], red[3][1]);
b1.setPosition(blue[0,0],blue[0,1]);
b2.setPosition(blue[1,0],blue[1,1]);
b3.setPosition(blue[2,0],blue[2,1]);
b4.setPosition(blue[3,0],blue[3,1]);
g1.setPosition(green[0,0], green[0,1]);
g2.setPosition(green[1,0], green[1,1]);
g3.setPosition(green[2,0], green[2,1]);
g4.setPosition(green[3,0], green[3,1]);
y1.setPosition(yellow[0,0], yellow[0,1]);
y2.setPosition(yellow[1,0], yellow[1,1]);
y3.setPosition(yellow[2,0], yellow[2,1]);
y4.setPosition(yellow[3,0], yellow[3,1]);

**Comment by PAWEENNUTpuyfai** [comment]
r1.setPosition(red[0][0], red[0][1]);
r2.setPosition(red[1][0], red[1][1]);
r3.setPosition(red[2][0], red[2][1]);
r4.setPosition(red[3][0], red[3][1]);
b1.setPosition(blue[0][0],blue[0][1]);
b2.setPosition(blue[1][0],blue[1][1]);
b3.setPosition(blue[2][0],blue[2][1]);
b4.setPosition(blue[3][0],blue[3][1]);
g1.setPosition(green[0][0], green[0][1]);
g2.setPosition(green[1][0], green[1][1]);
g3.setPosition(green[2][0], green[2][1]);
g4.setPosition(green[3][0], green[3][1]);
y1.setPosition(yellow[0][0], yellow[0][1]);
y2.setPosition(yellow[1][0], yellow[1][1]);
y3.setPosition(yellow[2][0], yellow[2][1]);
y4.setPosition(yellow[3][0], yellow[3][1]);

**Comment by MindIssawara** [comment]
window.draw(r1);

**Comment by PAWEENNUTpuyfai** [comment]
window.draw(r1);
window.draw(r2);
window.draw(r3);
window.draw(r4);
window.draw(b1);
window.draw(b2);
window.draw(b3);
window.draw(b4);
window.draw(g1);
window.draw(g2);
window.draw(g3);
window.draw(g4);
window.draw(y1);
window.draw(y2);
window.draw(y3);
window.draw(y4);

**Comment by PAWEENNUTpuyfai** [comment]
if (xc >= 450 && xc <= 500 && yc >= 175 && yc <= 225) getstart(xc ,yc, green[0][0], green[0][1]);
if (xc >= 550 && xc <= 600 && yc >= 175 && yc <= 225) getstart(xc, yc, green[1][0], green[1][1]);
if (xc >= 450 && xc <= 500 && yc >= 275 && yc <= 325) getstart(xc, yc, green[2][0], green[2][1]);
if (xc >= 550 && xc <= 600 && yc >= 275 && yc <= 325) getstart(xc, yc, green[3][0], green[3][1]);
if (xc >= 900 && xc <= 950 && yc >= 175 && yc <= 225) getstart(xc, yc, yellow[0][0], yellow[0][1]);
if (xc >= 1000 && xc <= 1050 && yc >= 175 && yc <= 225) getstart(xc, yc, yellow[1][0], yellow[1][1]);
if (xc >= 900 && xc <= 950 && yc >= 275 && yc <= 325) getstart(xc, yc, yellow[2][0], yellow[2][1]);
if (xc >= 1000 && xc <= 1050 && yc >= 275 && yc <= 325) getstart(xc, yc, yellow[3][0], yellow[3][1]);
if (xc >= 900 && xc <= 950 && yc >= 625 && yc <= 675) getstart(xc, yc, blue[0][0], blue[0][1]);
if (xc >= 1000 && xc <= 1050 && yc >= 625 && yc <= 675) getstart(xc, yc, blue[1][0], blue[1][1]);
if (xc >= 900 && xc <= 950 && yc >= 725 && yc <= 775) getstart(xc, yc, blue[2][0], blue[2][1]);
if (xc >= 900 && xc <= 1050 && yc >= 725 && yc <= 775) getstart(xc, yc, blue[3][0], blue[3][1]);
if (xc >= 450 && xc <= 500 && yc >= 625 && yc <= 675) getstart(xc, yc, red[0][0], red[0][1]);
if (xc >= 550 && xc <= 600 && yc >= 625 && yc <= 675) getstart(xc, yc, red[1][0], red[1][1]);
if (xc >= 450 && xc <= 500 && yc >= 725 && yc <= 775) getstart(xc, yc, red[2][0], red[2][1]);
if (xc >= 550 && xc <= 600 && yc >= 725 && yc <= 775) getstart(xc, yc, red[3][0], red[3][1]);

**Comment by MindIssawara** [comment]
https://en.sfml-dev.org/forums/index.php?topic=3146.0

**Comment by MindIssawara** [comment]
โดยรวมใช้งานได้แล้ว เก็บรายละเอียดอีกทีในทำเกมให้สมบูรณ์
